name: Trigger auto deployment for newyorksubway-app-20220908143944

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'NewYorkSubway/**'
    - '.github/workflows/newyorksubway-app-20220908143944-AutoDeployTrigger-881745bf-799f-48f0-87cb-7d9396ce686b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: newyorksubway.azurecr.io
          username: ${{ secrets.NEWYORKSUBWAYAPP20220908143944_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWYORKSUBWAYAPP20220908143944_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: newyorksubway.azurecr.io/newyorksubway-app-20220908143944:${{ github.sha }}
          file: ./NewYorkSubway/Dockerfile
          context: ./NewYorkSubway/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWYORKSUBWAYAPP20220908143944_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n newyorksubway-app-20220908143944 -g SubwayApi --server newyorksubway.azurecr.io --username  ${{ secrets.NEWYORKSUBWAYAPP20220908143944_REGISTRY_USERNAME }} --password ${{ secrets.NEWYORKSUBWAYAPP20220908143944_REGISTRY_PASSWORD }}
            az containerapp update -n newyorksubway-app-20220908143944 -g SubwayApi --image newyorksubway.azurecr.io/newyorksubway-app-20220908143944:${{ github.sha }}
